### ISSUE TITLE
Go to specific week

### ISSUE THREAD

**Issue by 92pino** [FaiChou/react-native-slideable-calendar-strip#13]
Thank you so much for the quick response to the last issue. 😊
![스크린샷 2020-01-06 오후 4 49 25](https://user-images.githubusercontent.com/45158632/71803693-d6848400-30a4-11ea-85e9-0233542c566c.png)

I would like to ask you one more question.

If you use react-native-datepicker to select a distant future date like the following image, I wonder if there is a way to move to that date from react-native-slideable-calendar-strip.

**Comment by 92pino** [comment]
![스크린샷 2020-01-06 오후 4 53 15](https://user-images.githubusercontent.com/45158632/71811519-45b7a380-30b8-11ea-8879-7861c3a75c7a.png)

In the present react-native-slideable-calendar-strip, it is included in the present week for two weeks in front and back. If you go to a distant future or a distant past using the react-native-datepicker, can you move mainly from the react-native-slideable-calendar-strip containing the date?

**Comment by FaiChou** [comment]
@92pino 

You can use `selectedDate ` property to set a day in future or past. Check the source code [here](https://github.com/FaiChou/react-native-slideable-calendar-strip/blob/master/lib/CalendarStrip.js#L139):

```javascript
        if (isFuture(nextSelectedDate)) {
          const head = this.state.datas[0];
          const tail = endOfWeek(nextSelectedDate, { weekStartsOn: nextProps.weekStartsOn });
          const days = eachDay(head, tail);
          this.setState({
            datas: days,
            isTodayVisible: false,
          }, () => {
            const page = ~~(days.length/7 - 1);
            // to last page
            this.scrollToPage(page);
          });
        } 
```

If you set a new `selectedDate`, the `componentWillReceiveProps ` can deal with the date for spawning uninitialized dates.

But if you set a date far more future, the cost is large and may cause slowly performance.
