### ISSUE TITLE
How to set limit to the date?

### ISSUE THREAD

**Issue by sojimon** [FaiChou/react-native-slideable-calendar-strip#2]
Hi, 
 I have a situation that need to show five days before the current date along with next 30 days.How can I do it?.

**Comment by FaiChou** [comment]
Start from five days before, end with next 25 days..  sounds like device cannot afford so many days on one page. Can you describe more ? or show me your UI.png?

**Comment by FaiChou** [comment]
And if today is Sunday, in the calendar **show five days before** it's Monday, but where the Saturday ? it's empty? 

And about the limit date feature I will add this week.

Thanks for issue me.

**Comment by anilkumar1505** [comment]
@FaiChou  is it possible component localization in English.

**Comment by FaiChou** [comment]
@anilkumar1505  hi, 0.3.1 supports English as default props.

<img width="451" alt="xnip2018-11-19_09-32-37" src="https://user-images.githubusercontent.com/18500846/48681557-1442f680-ebde-11e8-8ace-c97aad4fa44f.png">

**Comment by anilkumar1505** [comment]
Thanks !!!! lot it is working
