### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by SpriteLJL** [FaiChou/react-native-slideable-calendar-strip#3]
如果能设置第一天是星期一，以及下拉默认按月显示就更好了

**Comment by FaiChou** [comment]
谢谢, 功能做出来, 只是还没来及写api, 您如果有时间可以尝试修改下代码, 代码并不复杂, 有什么问题随时联系.

PS: 按月显示这个不符合此项目要求, 因为这只是个 **strip**, 您可以配合`react-native-calendars`, 使用暴露出来的接口:

```
      onSwipeDown={() => {
        alert('onSwipeDown');
      }}
```

**Comment by FaiChou** [comment]
onSwipeDown={() => {
            alert('onSwipeDown');
          }}
