### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by skyliwq** [FaiChou/react-native-slideable-calendar-strip#4]
开启Debug时候速度特别快 关闭Debug速度非常慢 请问问题出现在哪里？

**Comment by FaiChou** [comment]
@skyliwq  谢谢, 请问你用的是iOS还是安卓? 模拟器还是真机?

一般情况下都是开启debug会变慢, 关闭debug会变快. 

执行 `$ react-native info` 看下你的环境信息.

**Comment by skyliwq** [comment]
是在真机调试关闭Debug时候速度反而变慢，如果快速滑动的话会有卡顿空白 android ios 一样

**Comment by FaiChou** [comment]
你是说 iOS/Android 真机不开启 debug js remotely 时滑动卡顿.

这个还真没有遇到过, 你的当前页面只有这个日历滑动条么? 还有其他的业务逻辑么? 会不会是其他的业务逻辑控件占用太大内存导致卡顿? 我这里也没法复现,  有些卡顿问题只是因为调试时候卡顿, 打包release后就不会出现. 

能提供一些其他的详细信息么? 页面逻辑啥样? 能上传个卡顿的视频? 具体怎么用的?
