### ISSUE TITLE
样式建议

### ISSUE THREAD

**Issue by QiuMingx** [FaiChou/react-native-slideable-calendar-strip#5]
安卓开启showChineseLunar是，日期文字紧贴顶部下面空白太多，是否增加顶部内边距

**Comment by FaiChou** [comment]
@Qiluzz  好的.

有3个解决方案:
1. 有时间我fix, 发布下一版本
2. 您帮我fix, 提一个pr
3. fork下用自己的branch

祝使用愉快~

**Comment by FaiChou** [comment]
在代码的 69 行 https://github.com/FaiChou/react-native-slideable-calendar-strip/blob/master/lib/CalendarStrip.js#L69 添加:

```
marginTop: 3
```
