### ISSUE TITLE
How can I set Start day is Monday instead of Sunday?

### ISSUE THREAD

**Issue by vandiepbui** [FaiChou/react-native-slideable-calendar-strip#7]
How can I set Start day is Monday instead of Sunday?

**Comment by IceDev-xyz** [comment]
I would also love to have this as an option.

**Comment by IceDev-xyz** [comment]
For anyone interested, while the owner makes this possible. The fix is in `CalendarStrip.js` line 177

`const startLast2Week = startOfWeek(last2WeekOfToday, { weekStartsOn: 1 });`

For more info: https://date-fns.org/v2.1.0/docs/startOfWeek

You will also want to update `WEEK_en` in Weeks.js

**Comment by FaiChou** [comment]
@vandiepbui 
@IceDev-xyz 

0.4.0 supports for `weekStartsOn`:

```
<CalendarStrip
  selectedDate={this.state.selectedDate}
  onPressDate={(date) => {
    this.setState({ selectedDate: date });
  }}
  weekStartsOn={1} // 0,1,2,3,4,5,6 for S M T W T F S, defaults to 0
/>
```

**Comment by FaiChou** [comment]
![image](https://user-images.githubusercontent.com/18500846/64751970-87906d00-d550-11e9-84fe-f4a019aff3e6.png)

**Comment by IceDev-xyz** [comment]
Great! Thanks.
